### ISSUE TITLE
❓ how would you implement the Model class for the DockablePanel

### ISSUE THREAD

**Issue by cesarecaoduro** [ksobon/Masterclass#2]
I can see the MVVM is implemented partially here as we don't really have the Model class implemented.
I have implemented a messenger on the document changed event that should give me what I need, but just curious to know what would be the best approach?
This is what I have now (using MVVMToolkit)
in the ```AppCommand.cs```
```csharp
private void ViewActivated(object sender, ViewActivatedEventArgs e)
        {
            if (CurrentDocument != e.Document)
            {
                CurrentDocument = e.Document;
                WeakReferenceMessenger.Default.Send(new DocumentChangedMessage(CurrentDocument));
            }
        }
```
The message wrapper
```csharp
public class DocumentChangedMessage : ValueChangedMessage<Document>
    {
        public DocumentChangedMessage(Document value) : base(value)
        {
        }
    }
```
And in the ```ViewModel.cs```
```csharp
public partial class DummyDockablePanelViewModel : ObservableObject
    {
        [ObservableProperty]
        private string _documentTitle;    

        public DummyDockablePanelViewModel()
        {
            WeakReferenceMessenger.Default.Register<DocumentChangedMessage>(this, (r, m) =>
            {
                // Handle the message here, with r being the recipient and m being the
                // input message. Using the recipient passed as input makes it so that
                // the lambda expression doesn't capture "this", improving performance.
            });
        }
    }
```

Cheers!

**Comment by ksobon** [comment]
@cesarecaoduro Yeah, this isn't a *PURE* MVVM pattern. I usually split this up like this:
- View - XAML stuff
- View Model - anything that talks to the View. What happens when you push the button etc. 
- Model - anything that interacts with Revit. For example I would collect elements here that I need to build the UI, or if I interact with the Revit database from the UI, I process UI requests here. 

Now, for the Model. If I have a modeless dialog view.Show(), then Model is just passing messages back and forth from the External Event Handler. If I have a modal dialog view.ShowDialog() then I can execute code that talks to the Revit database here. It all depends how I want to talk to the Revit database. 

In your example, where you have an event, and you are setting up a message, I would do it just like you did it. Catch it, send it to the Model. If that message affects the UI, I might send it to the view model directly and bypass model.

**Comment by cesarecaoduro** [comment]
Cool thanks.
Great work on the workshop, looking forward to this year topics.
